config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'books#index'
  resources :books
  resources :searches


   get '/search' => 'books#search', :as => 'search_page'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  has_many :taggings, dependent: :destroy
  accepts_nested_attributes_for :taggings

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
      @books = Book.all
      @book = Book.new
      # render json: @books
  end


  def search
      @book = Book.new
   respond_to do |format|
      @search_results_books =  Book.joins(:taggings).where('tag_name like :query OR name like :query', query: "%#{params[:search]}%").uniq
      format.js {render partial: 'search'}
   end
  end


  def show
      @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])

  end

  
  def new
    @book = Book.new
    @book.taggings.build
  end

  def create
    @book = Book.create(book_params)

    respond_to do |format|
      if @book.save
        format.js     
      else
        format.js     
      end
    end
  end

  def update
    @book = Book.find(params[:id])

    respond_to do |format|
      if @book.update(book_params)
        format.js   
      else
        format.js
      end
    end
  end

  def destroy
    @book = Book.find(params[:id])

    @book.destroy
 
    respond_to do |format|
      format.js
    end
  end

  private

      def book_params
      params.require(:book).permit(:id, :name, :description, taggings_attributes: [:id, :tag_name])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def link_to_add_fields(name, f, association)

		new_object = f.object.send(association).klass.new
		id = new_object.object_id
		fields = f.fields_for(association, new_object, child_index: id) do |builder|
		render(association.to_s.singularize + "_fields", f: builder)
	    end

	    link_to(name, '#', class: 'add_fields', data: {id: id, fields: fields.gsub("\n", "")})
	end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/seraches_helper.rb
module SerachesHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/books/_book.html.erb
<div class="col-md-4 blog-main box text" id="book_<%= book.id %>" >
      
      <div class="panel panel-info">
        <div class="panel-heading">
          <h3 class="panel-name"><%= book.name %></h3>
          <h6 class="panel-description"><%= book.description %></h6>
          <h6 class="panel-tag_name"><b><%= book.taggings.map(&:tag_name).join(", ") %></b></h6>
        </div>


        <div class="panel-body">
          <br>

          <div class="btn-group" role="group" aria-label="...">
            <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#myupdatebook_<%= book.id %>">
            Edit
            </button>
            <%= link_to 'Destroy', book, method: :delete, remote: true, data: { confirm: 'Are you sure?'} %>
          </div>
        </div>
      
      </div>


<!-- Button trigger modal -->

<!-- Modal -->
<%= form_for(book, :method => :put, remote: true) do |form| %>

  <div class="modal fade" id="myupdatebook_<%= book.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="myModalLabel">Edit</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

         <div class="field">
          <%= form.label :name %><br>
          <%= form.text_field :name, class: "form-control book_name"%>
         </div>

         <div class="field">
          <%= form.label :description %><br>
          <%= form.text_field :description, class: "form-control book_description" %>
         </div>

         <div class="field">
          <%= form.fields_for :taggings do |f| %>
          <%= render 'tagging_fields', f:f %>
          <% end %>
          <%=link_to_add_fields 'Add Tag', form, :taggings%>
         </div>

      </div>
      <div class="modal-footer">
        <button type="button" id="myupdatebutton_<% book.id %>" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag "Update", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  </div>
<% end %>

</div>

app/views/books/_results.html.erb
<div class="container">

    <div id="container_books">
         <%= render @search_results_books %>
    </div>
</div>d

app/views/books/_search.js.erb
$("#mysearchbook").hide();
$("#search-results").html("<%= escape_javascript(render :partial => 'results') %>");

app/views/books/_tagging_fields.html.erb
<%= f.label :tag_name %>
<%= f.text_field :tag_name %>

<%= f.hidden_field :_destroy %>

 <!-- <%= link_to "Remove", class: 'remove-fields' %> -->

app/views/books/create.js.erb
$("#mynewbook").modal('hide');
$(".book_name").val('');
$(".book_description").val('');
$(".book_taggings").val('');


$("#container_books").prepend('<%= j render @book %>');

app/views/books/destroy.js.erb
$("#book_<%= @book.id %>").remove();

app/views/books/index.html.erb
<div class="container" id="mysearchbook" >
      
      <div class="row">
        <div class="text-center">
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mynewbook">
            New Book
            </button>
          
        </div>
      </div>
      <br>
      <hr>

      <div id="container_books">
         <%= render @books %>
      </div>


<!-- Button trigger modal -->

<!-- Modal -->
<%= form_for(@book, remote: true) do |form| %>

  <div class="modal fade" id="mynewbook" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">

         <div class="field">
          <%= form.label :name %><br>
          <%= form.text_field :name, class: "form-control book_name"%>
         </div>

         <div class="field">
          <%= form.label :description %><br>
          <%= form.text_field :description, class: "form-control book_description" %>
         </div>

         <div class="field">
          <%= form.fields_for :taggings do |f| %>
          <%= render 'tagging_fields', f:f %>
          <% end %>
          <%=link_to_add_fields 'Add Tag', form, :taggings%>
         </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <%= submit_tag "Create", class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  </div>
<% end %>

</div>

<div id="search-results">

</div>
<script >

  $('form').on('click', '.add_fields', function(event){
    console.log('clicked')
    var regexp, time;
    time = new Date().getTime();
    regexp = new RegExp($(this).data('id'), 'g');
    $(this).before($(this).data('fields').replace(regexp, time));
    return event.preventDefault();
  });


</script>

app/views/books/update.js.erb
$("#myupdatebook_<%= @book.id %>").modal('hide');
$("#book_<%= @book.id %>").replaceWith('<%= j render @book %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BooksStore</title>
    <link rel= "stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body><br>
    <%= form_tag(search_page_path, :method => "get", remote: true) do %>  
              <%= search_field_tag :search, params[:search], placeholder: "Search", class: "form-control" %> 
                <%= submit_tag "Search" %>

    <% end %>
    <%= link_to 'Home', root_path%>
  <nav>
    <br>
  
  <div>
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link btn btn-primary'  %>
 </div>
  </nav>
  
    <%= yield %>
  </body>
</html>